### ISSUE TITLE
Gracefully handle failures of username not being found.

### ISSUE THREAD

**Issue by lokiiarora** [RocktimSaikia/github-feed-cli#4]
Currently when there is no global git name set, it throws an error like the one shown below:
We could have a better flow by asking a user their username before trying to load the feed. 
<img width="1438" alt="Screen Shot 2020-10-11 at 6 44 39 PM" src="https://user-images.githubusercontent.com/20043762/95679653-eca21080-0bf1-11eb-9737-07c3c0ffc292.png">

Willing to contribute on this.

**Comment by rocktimsaikia** [comment]
Actually It was because of lack of time. I kinda created [cheat script](https://github.com/RocktimSaikia/github-feed-cli/blob/master/lib/read-username.js) that run the `git config user.name` internally and tries to grab the default user name from `stdout` but I knew that may cause some errors on other OSS. So I thought of trying like [git-config](https://github.com/eugeneware/git-config/) which does that job but that lib also had some issues and not maintained anymore. So I ended up writing a lib for that my self this evening and was about to implement it. But if you want then you can implement it too.
Here is the lib : [https://github.com/RocktimSaikia/read-git-user](https://github.com/RocktimSaikia/read-git-user)

**Comment by lokiiarora** [comment]
But this would parse for only windows, because AFAIK `ini` files are a windows only thing?

**Comment by rocktimsaikia** [comment]
Works on Linux. I am using Manjaro KDE. I really don't like idea of adding your user name every time you do a fetch. Thats' why I am considering the approach of getting the user name by itself. Do you have any suggestions for this specfic issue ? .
Orelse we can detech the OS in `read-git-user` lib and fetch accordingly by changing the path to that specific OS .gitconfig file.

**Comment by lokiiarora** [comment]
The idea being:
- Try to fetch username automatically using the package.
- If it fails, prompt the user to enter it and store it in a config file in home directory, like aws-cli does..!

**Comment by rocktimsaikia** [comment]
Alright. PRs are welcome. Create a seperate issue for this one 

>     * Try to fetch username automatically using the package.
> 
>     * If it fails, prompt the user to enter it and store it in a config file in home directory, like aws-cli does..!

**Comment by lokiiarora** [comment]
Perfect ! 👍🏽

**Comment by rocktimsaikia** [comment]
@lokiiarora It seems that all OSS depends on the same `.gitconfig` ini file. So try to implement the parser first and if it works then make a pr with that first. So that until the prompt feature is ready ,people trying out the cli tool for the first time won't have to face the same issue.

**Comment by rocktimsaikia** [comment]
Fixed in this [commit](https://github.com/RocktimSaikia/github-feed-cli/commit/cd28887446131765a0bd174b0a20469f6255961e)
